Update GitHub-Actions.yml
omanpios/Selenium-training pull request #8
Opened 2021-09-16 23:01 UTC by omanpios

2021-09-20 15:28 UTC, aperdomob requested changes

2021-09-20 15:28 UTC, aperdomob commented on .github/workflows/GitHub-Actions.yml
> +    branches: [ main ]
why do you execute in PR?
Also, execute only the test, you don't need to package this solution

2021-09-20 21:41 UTC, omanpios commented
Let it executing just with push and corrected the run with test not package

2021-09-21 16:42 UTC, aperdomob requested changes

2021-09-21 16:42 UTC, aperdomob commented on .github/workflows/GitHub-Actions.yml
> +      - name: Step 1 - Checkout main branch from GitHub
Remove Step
Only put 'Checkout'

2021-09-21 16:42 UTC, aperdomob commented on .github/workflows/GitHub-Actions.yml
> +    branches: [ main ]
evita tantos enters, los enters dividen bloques y no es claro que tratas de dividir con los enters

2021-09-21 16:42 UTC, aperdomob commented on .github/workflows/GitHub-Actions.yml
> +          java-version: 11
porque necesita un paso para hacer set de la versión de java

2021-09-21 16:42 UTC, aperdomob commented on .github/workflows/GitHub-Actions.yml
> +          ls -R
para que esto?

2021-09-21 17:21 UTC, omanpios commented on .github/workflows/GitHub-Actions.yml
> +    branches: [ main ]
Done

2021-09-21 17:22 UTC, omanpios commented on .github/workflows/GitHub-Actions.yml
> +          java-version: 11
Done

2021-09-21 18:02 UTC, aperdomob approved these changes

2021-09-21 18:02 UTC, merged